-- Initial testing accounts
INSERT INTO ACCOUNT (OWNER_NAME, BALANCE, VERSION)
VALUES ('Jane Heo', 1000.00, 0);

INSERT INTO ACCOUNT (OWNER_NAME, BALANCE, VERSION)
VALUES ('Rich Financial', 500.00, 0);